/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlternativeDistributionKeyCreateRequestDataAttributes } from '../models/AlternativeDistributionKeyCreateRequestDataAttributes.ts';
import { AlternativeDistributionKeyCreateRequestDataRelationships } from '../models/AlternativeDistributionKeyCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class AlternativeDistributionKeyCreateRequestData {
    'type': AlternativeDistributionKeyCreateRequestDataTypeEnum;
    'attributes': AlternativeDistributionKeyCreateRequestDataAttributes;
    'relationships': AlternativeDistributionKeyCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AlternativeDistributionKeyCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AlternativeDistributionKeyCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AlternativeDistributionKeyCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AlternativeDistributionKeyCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AlternativeDistributionKeyCreateRequestDataTypeEnum {
    AlternativeDistributionKeys = 'alternativeDistributionKeys'
}

