/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class AnalyticsReportInstanceAttributes {
    'granularity'?: AnalyticsReportInstanceAttributesGranularityEnum;
    'processingDate'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "granularity",
            "baseName": "granularity",
            "type": "AnalyticsReportInstanceAttributesGranularityEnum",
            "format": ""
        },
        {
            "name": "processingDate",
            "baseName": "processingDate",
            "type": "string",
            "format": "date"
        }    ];

    static getAttributeTypeMap() {
        return AnalyticsReportInstanceAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AnalyticsReportInstanceAttributesGranularityEnum {
    Daily = 'DAILY',
    Weekly = 'WEEKLY',
    Monthly = 'MONTHLY'
}

