/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppAvailabilityCreateRequestDataRelationships } from '../models/AppAvailabilityCreateRequestDataRelationships.ts';
import { AppAvailabilityV2CreateRequestDataAttributes } from '../models/AppAvailabilityV2CreateRequestDataAttributes.ts';
import { HttpFile } from '../http/http.ts';

export class AppAvailabilityCreateRequestData {
    'type': AppAvailabilityCreateRequestDataTypeEnum;
    'attributes': AppAvailabilityV2CreateRequestDataAttributes;
    'relationships': AppAvailabilityCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppAvailabilityCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppAvailabilityV2CreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppAvailabilityCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppAvailabilityCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppAvailabilityCreateRequestDataTypeEnum {
    AppAvailabilities = 'appAvailabilities'
}

