/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppAvailabilityV2CreateRequestData } from '../models/AppAvailabilityV2CreateRequestData.ts';
import { TerritoryAvailabilityInlineCreate } from '../models/TerritoryAvailabilityInlineCreate.ts';
import { HttpFile } from '../http/http.ts';

export class AppAvailabilityV2CreateRequest {
    'data': AppAvailabilityV2CreateRequestData;
    'included'?: Array<TerritoryAvailabilityInlineCreate>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "AppAvailabilityV2CreateRequestData",
            "format": ""
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<TerritoryAvailabilityInlineCreate>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppAvailabilityV2CreateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

