/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipAdvancedExperienceCreateRequestDataAttributes } from '../models/AppClipAdvancedExperienceCreateRequestDataAttributes.ts';
import { AppClipAdvancedExperienceCreateRequestDataRelationships } from '../models/AppClipAdvancedExperienceCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class AppClipAdvancedExperienceCreateRequestData {
    'type': AppClipAdvancedExperienceCreateRequestDataTypeEnum;
    'attributes': AppClipAdvancedExperienceCreateRequestDataAttributes;
    'relationships': AppClipAdvancedExperienceCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppClipAdvancedExperienceCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppClipAdvancedExperienceCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppClipAdvancedExperienceCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppClipAdvancedExperienceCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppClipAdvancedExperienceCreateRequestDataTypeEnum {
    AppClipAdvancedExperiences = 'appClipAdvancedExperiences'
}

