/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipDefaultExperienceLocalizationUpdateRequestDataAttributes } from '../models/AppClipDefaultExperienceLocalizationUpdateRequestDataAttributes.ts';
import { HttpFile } from '../http/http.ts';

export class AppClipDefaultExperienceLocalizationUpdateRequestData {
    'type': AppClipDefaultExperienceLocalizationUpdateRequestDataTypeEnum;
    'id': string;
    'attributes'?: AppClipDefaultExperienceLocalizationUpdateRequestDataAttributes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppClipDefaultExperienceLocalizationUpdateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppClipDefaultExperienceLocalizationUpdateRequestDataAttributes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppClipDefaultExperienceLocalizationUpdateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppClipDefaultExperienceLocalizationUpdateRequestDataTypeEnum {
    AppClipDefaultExperienceLocalizations = 'appClipDefaultExperienceLocalizations'
}

