/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppAvailabilityRelationshipsApp } from '../models/AppAvailabilityRelationshipsApp.ts';
import { AppCustomProductPageRelationshipsAppCustomProductPageVersions } from '../models/AppCustomProductPageRelationshipsAppCustomProductPageVersions.ts';
import { HttpFile } from '../http/http.ts';

export class AppCustomProductPageRelationships {
    'app'?: AppAvailabilityRelationshipsApp;
    'appCustomProductPageVersions'?: AppCustomProductPageRelationshipsAppCustomProductPageVersions;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "app",
            "baseName": "app",
            "type": "AppAvailabilityRelationshipsApp",
            "format": ""
        },
        {
            "name": "appCustomProductPageVersions",
            "baseName": "appCustomProductPageVersions",
            "type": "AppCustomProductPageRelationshipsAppCustomProductPageVersions",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppCustomProductPageRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

