/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipAdvancedExperienceUpdateRequestDataAttributes } from '../models/AppClipAdvancedExperienceUpdateRequestDataAttributes.ts';
import { AppClipAdvancedExperienceUpdateRequestDataRelationships } from '../models/AppClipAdvancedExperienceUpdateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class AppClipAdvancedExperienceUpdateRequestData {
    'type': AppClipAdvancedExperienceUpdateRequestDataTypeEnum;
    'id': string;
    'attributes'?: AppClipAdvancedExperienceUpdateRequestDataAttributes;
    'relationships'?: AppClipAdvancedExperienceUpdateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppClipAdvancedExperienceUpdateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppClipAdvancedExperienceUpdateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppClipAdvancedExperienceUpdateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppClipAdvancedExperienceUpdateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppClipAdvancedExperienceUpdateRequestDataTypeEnum {
    AppClipAdvancedExperiences = 'appClipAdvancedExperiences'
}

