/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipAdvancedExperienceRelationshipsAppClip } from '../models/AppClipAdvancedExperienceRelationshipsAppClip.ts';
import { AppClipAdvancedExperienceRelationshipsHeaderImage } from '../models/AppClipAdvancedExperienceRelationshipsHeaderImage.ts';
import { AppClipAdvancedExperienceRelationshipsLocalizations } from '../models/AppClipAdvancedExperienceRelationshipsLocalizations.ts';
import { HttpFile } from '../http/http.ts';

export class AppClipAdvancedExperienceRelationships {
    'appClip'?: AppClipAdvancedExperienceRelationshipsAppClip;
    'headerImage'?: AppClipAdvancedExperienceRelationshipsHeaderImage;
    'localizations'?: AppClipAdvancedExperienceRelationshipsLocalizations;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appClip",
            "baseName": "appClip",
            "type": "AppClipAdvancedExperienceRelationshipsAppClip",
            "format": ""
        },
        {
            "name": "headerImage",
            "baseName": "headerImage",
            "type": "AppClipAdvancedExperienceRelationshipsHeaderImage",
            "format": ""
        },
        {
            "name": "localizations",
            "baseName": "localizations",
            "type": "AppClipAdvancedExperienceRelationshipsLocalizations",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppClipAdvancedExperienceRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

