/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export enum AppClipAdvancedExperienceLanguage {
    Ar = 'AR',
    Ca = 'CA',
    Cs = 'CS',
    Da = 'DA',
    De = 'DE',
    El = 'EL',
    En = 'EN',
    Es = 'ES',
    Fi = 'FI',
    Fr = 'FR',
    He = 'HE',
    Hi = 'HI',
    Hr = 'HR',
    Hu = 'HU',
    Id = 'ID',
    It = 'IT',
    Ja = 'JA',
    Ko = 'KO',
    Ms = 'MS',
    Nl = 'NL',
    No = 'NO',
    Pl = 'PL',
    Pt = 'PT',
    Ro = 'RO',
    Ru = 'RU',
    Sk = 'SK',
    Sv = 'SV',
    Th = 'TH',
    Tr = 'TR',
    Uk = 'UK',
    Vi = 'VI',
    Zh = 'ZH'
}
