/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppCustomProductPageVersionCreateRequestDataRelationshipsAppCustomProductPage } from '../models/AppCustomProductPageVersionCreateRequestDataRelationshipsAppCustomProductPage.ts';
import { AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizations } from '../models/AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizations.ts';
import { HttpFile } from '../http/http.ts';

export class AppCustomProductPageVersionCreateRequestDataRelationships {
    'appCustomProductPage': AppCustomProductPageVersionCreateRequestDataRelationshipsAppCustomProductPage;
    'appCustomProductPageLocalizations'?: AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizations;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appCustomProductPage",
            "baseName": "appCustomProductPage",
            "type": "AppCustomProductPageVersionCreateRequestDataRelationshipsAppCustomProductPage",
            "format": ""
        },
        {
            "name": "appCustomProductPageLocalizations",
            "baseName": "appCustomProductPageLocalizations",
            "type": "AppCustomProductPageVersionInlineCreateRelationshipsAppCustomProductPageLocalizations",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppCustomProductPageVersionCreateRequestDataRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

