/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipAdvancedExperienceUpdateRequestDataRelationshipsAppClip } from '../models/AppClipAdvancedExperienceUpdateRequestDataRelationshipsAppClip.ts';
import { AppClipAdvancedExperienceUpdateRequestDataRelationshipsHeaderImage } from '../models/AppClipAdvancedExperienceUpdateRequestDataRelationshipsHeaderImage.ts';
import { AppClipAdvancedExperienceUpdateRequestDataRelationshipsLocalizations } from '../models/AppClipAdvancedExperienceUpdateRequestDataRelationshipsLocalizations.ts';
import { HttpFile } from '../http/http.ts';

export class AppClipAdvancedExperienceUpdateRequestDataRelationships {
    'appClip'?: AppClipAdvancedExperienceUpdateRequestDataRelationshipsAppClip;
    'headerImage'?: AppClipAdvancedExperienceUpdateRequestDataRelationshipsHeaderImage;
    'localizations'?: AppClipAdvancedExperienceUpdateRequestDataRelationshipsLocalizations;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appClip",
            "baseName": "appClip",
            "type": "AppClipAdvancedExperienceUpdateRequestDataRelationshipsAppClip",
            "format": ""
        },
        {
            "name": "headerImage",
            "baseName": "headerImage",
            "type": "AppClipAdvancedExperienceUpdateRequestDataRelationshipsHeaderImage",
            "format": ""
        },
        {
            "name": "localizations",
            "baseName": "localizations",
            "type": "AppClipAdvancedExperienceUpdateRequestDataRelationshipsLocalizations",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppClipAdvancedExperienceUpdateRequestDataRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

