/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipAppStoreReviewDetailCreateRequestDataRelationships } from '../models/AppClipAppStoreReviewDetailCreateRequestDataRelationships.ts';
import { AppClipDefaultExperienceLocalizationCreateRequestDataAttributes } from '../models/AppClipDefaultExperienceLocalizationCreateRequestDataAttributes.ts';
import { HttpFile } from '../http/http.ts';

export class AppClipDefaultExperienceLocalizationCreateRequestData {
    'type': AppClipDefaultExperienceLocalizationCreateRequestDataTypeEnum;
    'attributes': AppClipDefaultExperienceLocalizationCreateRequestDataAttributes;
    'relationships': AppClipAppStoreReviewDetailCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppClipDefaultExperienceLocalizationCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppClipDefaultExperienceLocalizationCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppClipAppStoreReviewDetailCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppClipDefaultExperienceLocalizationCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppClipDefaultExperienceLocalizationCreateRequestDataTypeEnum {
    AppClipDefaultExperienceLocalizations = 'appClipDefaultExperienceLocalizations'
}

