/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipAdvancedExperienceImageAttributes } from '../models/AppClipAdvancedExperienceImageAttributes.ts';
import { AppClipDefaultExperience } from '../models/AppClipDefaultExperience.ts';
import { AppClipHeaderImage } from '../models/AppClipHeaderImage.ts';
import { AppClipHeaderImageRelationships } from '../models/AppClipHeaderImageRelationships.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { HttpFile } from '../http/http.ts';

export class AppClipDefaultExperienceLocalizationsResponseIncludedInner {
    'type': AppClipDefaultExperienceLocalizationsResponseIncludedInnerTypeEnum;
    'id': string;
    'attributes'?: AppClipAdvancedExperienceImageAttributes;
    'relationships'?: AppClipHeaderImageRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppClipDefaultExperienceLocalizationsResponseIncludedInnerTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppClipAdvancedExperienceImageAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppClipHeaderImageRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppClipDefaultExperienceLocalizationsResponseIncludedInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppClipDefaultExperienceLocalizationsResponseIncludedInnerTypeEnum {
    AppClipDefaultExperiences = 'appClipDefaultExperiences',
    AppClipHeaderImages = 'appClipHeaderImages'
}

