/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipAdvancedExperienceAttributesPlaceDisplayPoint } from '../models/AppClipAdvancedExperienceAttributesPlaceDisplayPoint.ts';
import { AppClipAdvancedExperienceAttributesPlaceMainAddress } from '../models/AppClipAdvancedExperienceAttributesPlaceMainAddress.ts';
import { AppClipAdvancedExperienceAttributesPlacePhoneNumber } from '../models/AppClipAdvancedExperienceAttributesPlacePhoneNumber.ts';
import { HttpFile } from '../http/http.ts';

export class AppClipAdvancedExperienceAttributesPlace {
    'placeId'?: string;
    'names'?: Array<string>;
    'mainAddress'?: AppClipAdvancedExperienceAttributesPlaceMainAddress;
    'displayPoint'?: AppClipAdvancedExperienceAttributesPlaceDisplayPoint;
    'mapAction'?: AppClipAdvancedExperienceAttributesPlaceMapActionEnum;
    'relationship'?: AppClipAdvancedExperienceAttributesPlaceRelationshipEnum;
    'phoneNumber'?: AppClipAdvancedExperienceAttributesPlacePhoneNumber;
    'homePage'?: string;
    'categories'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "placeId",
            "baseName": "placeId",
            "type": "string",
            "format": ""
        },
        {
            "name": "names",
            "baseName": "names",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "mainAddress",
            "baseName": "mainAddress",
            "type": "AppClipAdvancedExperienceAttributesPlaceMainAddress",
            "format": ""
        },
        {
            "name": "displayPoint",
            "baseName": "displayPoint",
            "type": "AppClipAdvancedExperienceAttributesPlaceDisplayPoint",
            "format": ""
        },
        {
            "name": "mapAction",
            "baseName": "mapAction",
            "type": "AppClipAdvancedExperienceAttributesPlaceMapActionEnum",
            "format": ""
        },
        {
            "name": "relationship",
            "baseName": "relationship",
            "type": "AppClipAdvancedExperienceAttributesPlaceRelationshipEnum",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "AppClipAdvancedExperienceAttributesPlacePhoneNumber",
            "format": ""
        },
        {
            "name": "homePage",
            "baseName": "homePage",
            "type": "string",
            "format": ""
        },
        {
            "name": "categories",
            "baseName": "categories",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppClipAdvancedExperienceAttributesPlace.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppClipAdvancedExperienceAttributesPlaceMapActionEnum {
    BuyTickets = 'BUY_TICKETS',
    ViewAvailability = 'VIEW_AVAILABILITY',
    ViewPricing = 'VIEW_PRICING',
    HotelBookRoom = 'HOTEL_BOOK_ROOM',
    ParkingReserveParking = 'PARKING_RESERVE_PARKING',
    RestaurantJoinWaitlist = 'RESTAURANT_JOIN_WAITLIST',
    RestaurantOrderDelivery = 'RESTAURANT_ORDER_DELIVERY',
    RestaurantOrderFood = 'RESTAURANT_ORDER_FOOD',
    RestaurantOrderTakeout = 'RESTAURANT_ORDER_TAKEOUT',
    RestaurantReservation = 'RESTAURANT_RESERVATION',
    ScheduleAppointment = 'SCHEDULE_APPOINTMENT',
    RestaurantViewMenu = 'RESTAURANT_VIEW_MENU',
    TheaterNowPlaying = 'THEATER_NOW_PLAYING'
}
export enum AppClipAdvancedExperienceAttributesPlaceRelationshipEnum {
    Owner = 'OWNER',
    Authorized = 'AUTHORIZED',
    Other = 'OTHER'
}

