/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipAdvancedExperienceAttributesPlaceDisplayPointCoordinates } from '../models/AppClipAdvancedExperienceAttributesPlaceDisplayPointCoordinates.ts';
import { HttpFile } from '../http/http.ts';

export class AppClipAdvancedExperienceAttributesPlaceDisplayPoint {
    'coordinates'?: AppClipAdvancedExperienceAttributesPlaceDisplayPointCoordinates;
    'source'?: AppClipAdvancedExperienceAttributesPlaceDisplayPointSourceEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "coordinates",
            "baseName": "coordinates",
            "type": "AppClipAdvancedExperienceAttributesPlaceDisplayPointCoordinates",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "AppClipAdvancedExperienceAttributesPlaceDisplayPointSourceEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppClipAdvancedExperienceAttributesPlaceDisplayPoint.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppClipAdvancedExperienceAttributesPlaceDisplayPointSourceEnum {
    Calculated = 'CALCULATED',
    ManuallyPlaced = 'MANUALLY_PLACED'
}

