/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClip } from '../models/AppClip.ts';
import { AppClipAppStoreReviewDetail } from '../models/AppClipAppStoreReviewDetail.ts';
import { AppClipAppStoreReviewDetailAttributes } from '../models/AppClipAppStoreReviewDetailAttributes.ts';
import { AppClipAppStoreReviewDetailRelationships } from '../models/AppClipAppStoreReviewDetailRelationships.ts';
import { AppClipDefaultExperienceLocalization } from '../models/AppClipDefaultExperienceLocalization.ts';
import { AppStoreVersion } from '../models/AppStoreVersion.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { HttpFile } from '../http/http.ts';

export class AppClipDefaultExperiencesResponseIncludedInner {
    'type': AppClipDefaultExperiencesResponseIncludedInnerTypeEnum;
    'id': string;
    'attributes'?: AppClipAppStoreReviewDetailAttributes;
    'relationships'?: AppClipAppStoreReviewDetailRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppClipDefaultExperiencesResponseIncludedInnerTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppClipAppStoreReviewDetailAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppClipAppStoreReviewDetailRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppClipDefaultExperiencesResponseIncludedInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppClipDefaultExperiencesResponseIncludedInnerTypeEnum {
    AppClips = 'appClips',
    AppStoreVersions = 'appStoreVersions',
    AppClipDefaultExperienceLocalizations = 'appClipDefaultExperienceLocalizations',
    AppClipAppStoreReviewDetails = 'appClipAppStoreReviewDetails'
}

