/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipDefaultExperienceAttributes } from '../models/AppClipDefaultExperienceAttributes.ts';
import { AppClipDefaultExperienceUpdateRequestDataRelationships } from '../models/AppClipDefaultExperienceUpdateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class AppClipDefaultExperienceUpdateRequestData {
    'type': AppClipDefaultExperienceUpdateRequestDataTypeEnum;
    'id': string;
    'attributes'?: AppClipDefaultExperienceAttributes;
    'relationships'?: AppClipDefaultExperienceUpdateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppClipDefaultExperienceUpdateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppClipDefaultExperienceAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppClipDefaultExperienceUpdateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppClipDefaultExperienceUpdateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppClipDefaultExperienceUpdateRequestDataTypeEnum {
    AppClipDefaultExperiences = 'appClipDefaultExperiences'
}

