/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class AppEventAttributesTerritorySchedulesInner {
    'territories'?: Array<string>;
    'publishStart'?: Date;
    'eventStart'?: Date;
    'eventEnd'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "territories",
            "baseName": "territories",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "publishStart",
            "baseName": "publishStart",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "eventStart",
            "baseName": "eventStart",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "eventEnd",
            "baseName": "eventEnd",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return AppEventAttributesTerritorySchedulesInner.attributeTypeMap;
    }

    public constructor() {
    }
}

