/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppEventScreenshotCreateRequestDataRelationships } from '../models/AppEventScreenshotCreateRequestDataRelationships.ts';
import { AppEventVideoClipCreateRequestDataAttributes } from '../models/AppEventVideoClipCreateRequestDataAttributes.ts';
import { HttpFile } from '../http/http.ts';

export class AppEventVideoClipCreateRequestData {
    'type': AppEventVideoClipCreateRequestDataTypeEnum;
    'attributes': AppEventVideoClipCreateRequestDataAttributes;
    'relationships': AppEventScreenshotCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppEventVideoClipCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppEventVideoClipCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppEventScreenshotCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppEventVideoClipCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppEventVideoClipCreateRequestDataTypeEnum {
    AppEventVideoClips = 'appEventVideoClips'
}

