/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppEncryptionDeclarationState } from '../models/AppEncryptionDeclarationState.ts';
import { Platform } from '../models/Platform.ts';
import { HttpFile } from '../http/http.ts';

export class AppEncryptionDeclarationAttributes {
    'appDescription'?: string;
    'createdDate'?: Date;
    'usesEncryption'?: boolean;
    'exempt'?: boolean;
    'containsProprietaryCryptography'?: boolean;
    'containsThirdPartyCryptography'?: boolean;
    'availableOnFrenchStore'?: boolean;
    'platform'?: Platform;
    'uploadedDate'?: Date;
    'documentUrl'?: string;
    'documentName'?: string;
    'documentType'?: string;
    'appEncryptionDeclarationState'?: AppEncryptionDeclarationState;
    'codeValue'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appDescription",
            "baseName": "appDescription",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdDate",
            "baseName": "createdDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "usesEncryption",
            "baseName": "usesEncryption",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "exempt",
            "baseName": "exempt",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "containsProprietaryCryptography",
            "baseName": "containsProprietaryCryptography",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "containsThirdPartyCryptography",
            "baseName": "containsThirdPartyCryptography",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "availableOnFrenchStore",
            "baseName": "availableOnFrenchStore",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "Platform",
            "format": ""
        },
        {
            "name": "uploadedDate",
            "baseName": "uploadedDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "documentUrl",
            "baseName": "documentUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "documentName",
            "baseName": "documentName",
            "type": "string",
            "format": ""
        },
        {
            "name": "documentType",
            "baseName": "documentType",
            "type": "string",
            "format": ""
        },
        {
            "name": "appEncryptionDeclarationState",
            "baseName": "appEncryptionDeclarationState",
            "type": "AppEncryptionDeclarationState",
            "format": ""
        },
        {
            "name": "codeValue",
            "baseName": "codeValue",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppEncryptionDeclarationAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}



