/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppEventScreenshotAttributes } from '../models/AppEventScreenshotAttributes.ts';
import { AppEventScreenshotRelationships } from '../models/AppEventScreenshotRelationships.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { HttpFile } from '../http/http.ts';

export class AppEventScreenshot {
    'type': AppEventScreenshotTypeEnum;
    'id': string;
    'attributes'?: AppEventScreenshotAttributes;
    'relationships'?: AppEventScreenshotRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppEventScreenshotTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppEventScreenshotAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppEventScreenshotRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppEventScreenshot.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppEventScreenshotTypeEnum {
    AppEventScreenshots = 'appEventScreenshots'
}

