/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppEventAttributesTerritorySchedulesInner } from '../models/AppEventAttributesTerritorySchedulesInner.ts';
import { HttpFile } from '../http/http.ts';

export class AppEventCreateRequestDataAttributes {
    'referenceName': string;
    'badge'?: AppEventCreateRequestDataAttributesBadgeEnum;
    'deepLink'?: string;
    'purchaseRequirement'?: AppEventCreateRequestDataAttributesPurchaseRequirementEnum;
    'primaryLocale'?: string;
    'priority'?: AppEventCreateRequestDataAttributesPriorityEnum;
    'purpose'?: AppEventCreateRequestDataAttributesPurposeEnum;
    'territorySchedules'?: Array<AppEventAttributesTerritorySchedulesInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "referenceName",
            "baseName": "referenceName",
            "type": "string",
            "format": ""
        },
        {
            "name": "badge",
            "baseName": "badge",
            "type": "AppEventCreateRequestDataAttributesBadgeEnum",
            "format": ""
        },
        {
            "name": "deepLink",
            "baseName": "deepLink",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "purchaseRequirement",
            "baseName": "purchaseRequirement",
            "type": "AppEventCreateRequestDataAttributesPurchaseRequirementEnum",
            "format": ""
        },
        {
            "name": "primaryLocale",
            "baseName": "primaryLocale",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "AppEventCreateRequestDataAttributesPriorityEnum",
            "format": ""
        },
        {
            "name": "purpose",
            "baseName": "purpose",
            "type": "AppEventCreateRequestDataAttributesPurposeEnum",
            "format": ""
        },
        {
            "name": "territorySchedules",
            "baseName": "territorySchedules",
            "type": "Array<AppEventAttributesTerritorySchedulesInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppEventCreateRequestDataAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppEventCreateRequestDataAttributesBadgeEnum {
    LiveEvent = 'LIVE_EVENT',
    Premiere = 'PREMIERE',
    Challenge = 'CHALLENGE',
    Competition = 'COMPETITION',
    NewSeason = 'NEW_SEASON',
    MajorUpdate = 'MAJOR_UPDATE',
    SpecialEvent = 'SPECIAL_EVENT'
}
export enum AppEventCreateRequestDataAttributesPurchaseRequirementEnum {
    NoCostAssociated = 'NO_COST_ASSOCIATED',
    InAppPurchase = 'IN_APP_PURCHASE',
    Subscription = 'SUBSCRIPTION',
    InAppPurchaseAndSubscription = 'IN_APP_PURCHASE_AND_SUBSCRIPTION',
    InAppPurchaseOrSubscription = 'IN_APP_PURCHASE_OR_SUBSCRIPTION'
}
export enum AppEventCreateRequestDataAttributesPriorityEnum {
    High = 'HIGH',
    Normal = 'NORMAL'
}
export enum AppEventCreateRequestDataAttributesPurposeEnum {
    AppropriateForAllUsers = 'APPROPRIATE_FOR_ALL_USERS',
    AttractNewUsers = 'ATTRACT_NEW_USERS',
    KeepActiveUsersInformed = 'KEEP_ACTIVE_USERS_INFORMED',
    BringBackLapsedUsers = 'BRING_BACK_LAPSED_USERS'
}

