/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppEvent } from '../models/AppEvent.ts';
import { AppEventScreenshot } from '../models/AppEventScreenshot.ts';
import { AppEventScreenshotRelationships } from '../models/AppEventScreenshotRelationships.ts';
import { AppEventVideoClip } from '../models/AppEventVideoClip.ts';
import { AppEventVideoClipAttributes } from '../models/AppEventVideoClipAttributes.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { HttpFile } from '../http/http.ts';

export class AppEventLocalizationsResponseIncludedInner {
    'type': AppEventLocalizationsResponseIncludedInnerTypeEnum;
    'id': string;
    'attributes'?: AppEventVideoClipAttributes;
    'relationships'?: AppEventScreenshotRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppEventLocalizationsResponseIncludedInnerTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppEventVideoClipAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppEventScreenshotRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppEventLocalizationsResponseIncludedInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppEventLocalizationsResponseIncludedInnerTypeEnum {
    AppEvents = 'appEvents',
    AppEventScreenshots = 'appEventScreenshots',
    AppEventVideoClips = 'appEventVideoClips'
}

