/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppAvailabilityRelationshipsApp } from '../models/AppAvailabilityRelationshipsApp.ts';
import { AppCategoryRelationshipsParent } from '../models/AppCategoryRelationshipsParent.ts';
import { AppInfoRelationshipsAgeRatingDeclaration } from '../models/AppInfoRelationshipsAgeRatingDeclaration.ts';
import { AppInfoRelationshipsAppInfoLocalizations } from '../models/AppInfoRelationshipsAppInfoLocalizations.ts';
import { HttpFile } from '../http/http.ts';

export class AppInfoRelationships {
    'app'?: AppAvailabilityRelationshipsApp;
    'ageRatingDeclaration'?: AppInfoRelationshipsAgeRatingDeclaration;
    'appInfoLocalizations'?: AppInfoRelationshipsAppInfoLocalizations;
    'primaryCategory'?: AppCategoryRelationshipsParent;
    'primarySubcategoryOne'?: AppCategoryRelationshipsParent;
    'primarySubcategoryTwo'?: AppCategoryRelationshipsParent;
    'secondaryCategory'?: AppCategoryRelationshipsParent;
    'secondarySubcategoryOne'?: AppCategoryRelationshipsParent;
    'secondarySubcategoryTwo'?: AppCategoryRelationshipsParent;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "app",
            "baseName": "app",
            "type": "AppAvailabilityRelationshipsApp",
            "format": ""
        },
        {
            "name": "ageRatingDeclaration",
            "baseName": "ageRatingDeclaration",
            "type": "AppInfoRelationshipsAgeRatingDeclaration",
            "format": ""
        },
        {
            "name": "appInfoLocalizations",
            "baseName": "appInfoLocalizations",
            "type": "AppInfoRelationshipsAppInfoLocalizations",
            "format": ""
        },
        {
            "name": "primaryCategory",
            "baseName": "primaryCategory",
            "type": "AppCategoryRelationshipsParent",
            "format": ""
        },
        {
            "name": "primarySubcategoryOne",
            "baseName": "primarySubcategoryOne",
            "type": "AppCategoryRelationshipsParent",
            "format": ""
        },
        {
            "name": "primarySubcategoryTwo",
            "baseName": "primarySubcategoryTwo",
            "type": "AppCategoryRelationshipsParent",
            "format": ""
        },
        {
            "name": "secondaryCategory",
            "baseName": "secondaryCategory",
            "type": "AppCategoryRelationshipsParent",
            "format": ""
        },
        {
            "name": "secondarySubcategoryOne",
            "baseName": "secondarySubcategoryOne",
            "type": "AppCategoryRelationshipsParent",
            "format": ""
        },
        {
            "name": "secondarySubcategoryTwo",
            "baseName": "secondarySubcategoryTwo",
            "type": "AppCategoryRelationshipsParent",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppInfoRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

