/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppInfoUpdateRequestDataRelationships } from '../models/AppInfoUpdateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class AppInfoUpdateRequestData {
    'type': AppInfoUpdateRequestDataTypeEnum;
    'id': string;
    'relationships'?: AppInfoUpdateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppInfoUpdateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppInfoUpdateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppInfoUpdateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppInfoUpdateRequestDataTypeEnum {
    AppInfos = 'appInfos'
}

