/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppMediaStateError } from '../models/AppMediaStateError.ts';
import { HttpFile } from '../http/http.ts';

export class AppMediaAssetState {
    'errors'?: Array<AppMediaStateError>;
    'warnings'?: Array<AppMediaStateError>;
    'state'?: AppMediaAssetStateStateEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "errors",
            "baseName": "errors",
            "type": "Array<AppMediaStateError>",
            "format": ""
        },
        {
            "name": "warnings",
            "baseName": "warnings",
            "type": "Array<AppMediaStateError>",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "AppMediaAssetStateStateEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppMediaAssetState.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppMediaAssetStateStateEnum {
    AwaitingUpload = 'AWAITING_UPLOAD',
    UploadComplete = 'UPLOAD_COMPLETE',
    Complete = 'COMPLETE',
    Failed = 'FAILED'
}

