/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppPriceScheduleCreateRequestDataRelationships } from '../models/AppPriceScheduleCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class AppPriceScheduleCreateRequestData {
    'type': AppPriceScheduleCreateRequestDataTypeEnum;
    'relationships': AppPriceScheduleCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppPriceScheduleCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppPriceScheduleCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppPriceScheduleCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppPriceScheduleCreateRequestDataTypeEnum {
    AppPriceSchedules = 'appPriceSchedules'
}

