/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppAvailabilityResponseIncludedInner } from '../models/AppAvailabilityResponseIncludedInner.ts';
import { AppPricePointV3 } from '../models/AppPricePointV3.ts';
import { DocumentLinks } from '../models/DocumentLinks.ts';
import { HttpFile } from '../http/http.ts';

export class AppPricePointV3Response {
    'data': AppPricePointV3;
    'included'?: Array<AppAvailabilityResponseIncludedInner>;
    'links': DocumentLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "AppPricePointV3",
            "format": ""
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<AppAvailabilityResponseIncludedInner>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "DocumentLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppPricePointV3Response.attributeTypeMap;
    }

    public constructor() {
    }
}

