/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppCustomProductPageLocalization } from '../models/AppCustomProductPageLocalization.ts';
import { AppPreview } from '../models/AppPreview.ts';
import { AppPreviewAttributes } from '../models/AppPreviewAttributes.ts';
import { AppPreviewRelationships } from '../models/AppPreviewRelationships.ts';
import { AppStoreVersionExperimentTreatmentLocalization } from '../models/AppStoreVersionExperimentTreatmentLocalization.ts';
import { AppStoreVersionLocalization } from '../models/AppStoreVersionLocalization.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { HttpFile } from '../http/http.ts';

export class AppPreviewSetsResponseIncludedInner {
    'type': AppPreviewSetsResponseIncludedInnerTypeEnum;
    'id': string;
    'attributes'?: AppPreviewAttributes;
    'relationships'?: AppPreviewRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppPreviewSetsResponseIncludedInnerTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppPreviewAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppPreviewRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppPreviewSetsResponseIncludedInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppPreviewSetsResponseIncludedInnerTypeEnum {
    AppStoreVersionLocalizations = 'appStoreVersionLocalizations',
    AppCustomProductPageLocalizations = 'appCustomProductPageLocalizations',
    AppStoreVersionExperimentTreatmentLocalizations = 'appStoreVersionExperimentTreatmentLocalizations',
    AppPreviews = 'appPreviews'
}

