/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppPriceTier } from '../models/AppPriceTier.ts';
import { AppPriceTierRelationships } from '../models/AppPriceTierRelationships.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { Territory } from '../models/Territory.ts';
import { TerritoryAttributes } from '../models/TerritoryAttributes.ts';
import { HttpFile } from '../http/http.ts';

export class AppPricePointsResponseIncludedInner {
    'type': AppPricePointsResponseIncludedInnerTypeEnum;
    'id': string;
    'relationships'?: AppPriceTierRelationships;
    'links'?: ResourceLinks;
    'attributes'?: TerritoryAttributes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppPricePointsResponseIncludedInnerTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppPriceTierRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "TerritoryAttributes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppPricePointsResponseIncludedInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppPricePointsResponseIncludedInnerTypeEnum {
    AppPriceTiers = 'appPriceTiers',
    Territories = 'territories'
}

