/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class AppRelationshipsGameCenterDetailData {
    'type': AppRelationshipsGameCenterDetailDataTypeEnum;
    'id': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppRelationshipsGameCenterDetailDataTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppRelationshipsGameCenterDetailData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppRelationshipsGameCenterDetailDataTypeEnum {
    GameCenterDetails = 'gameCenterDetails'
}

