/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Platform } from '../models/Platform.ts';
import { HttpFile } from '../http/http.ts';

export class AppStoreVersionCreateRequestDataAttributes {
    'platform': Platform;
    'versionString': string;
    'copyright'?: string;
    'reviewType'?: AppStoreVersionCreateRequestDataAttributesReviewTypeEnum;
    'releaseType'?: AppStoreVersionCreateRequestDataAttributesReleaseTypeEnum;
    'earliestReleaseDate'?: Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "platform",
            "baseName": "platform",
            "type": "Platform",
            "format": ""
        },
        {
            "name": "versionString",
            "baseName": "versionString",
            "type": "string",
            "format": ""
        },
        {
            "name": "copyright",
            "baseName": "copyright",
            "type": "string",
            "format": ""
        },
        {
            "name": "reviewType",
            "baseName": "reviewType",
            "type": "AppStoreVersionCreateRequestDataAttributesReviewTypeEnum",
            "format": ""
        },
        {
            "name": "releaseType",
            "baseName": "releaseType",
            "type": "AppStoreVersionCreateRequestDataAttributesReleaseTypeEnum",
            "format": ""
        },
        {
            "name": "earliestReleaseDate",
            "baseName": "earliestReleaseDate",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionCreateRequestDataAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppStoreVersionCreateRequestDataAttributesReviewTypeEnum {
    AppStore = 'APP_STORE',
    Notarization = 'NOTARIZATION'
}
export enum AppStoreVersionCreateRequestDataAttributesReleaseTypeEnum {
    Manual = 'MANUAL',
    AfterApproval = 'AFTER_APPROVAL',
    Scheduled = 'SCHEDULED'
}

