/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AlternativeDistributionPackageCreateRequestDataRelationships } from '../models/AlternativeDistributionPackageCreateRequestDataRelationships.ts';
import { AppStoreVersionExperimentCreateRequestDataAttributes } from '../models/AppStoreVersionExperimentCreateRequestDataAttributes.ts';
import { HttpFile } from '../http/http.ts';

export class AppStoreVersionExperimentCreateRequestData {
    'type': AppStoreVersionExperimentCreateRequestDataTypeEnum;
    'attributes': AppStoreVersionExperimentCreateRequestDataAttributes;
    'relationships': AlternativeDistributionPackageCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppStoreVersionExperimentCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppStoreVersionExperimentCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AlternativeDistributionPackageCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionExperimentCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppStoreVersionExperimentCreateRequestDataTypeEnum {
    AppStoreVersionExperiments = 'appStoreVersionExperiments'
}

