/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class AppsBetaTesterUsagesV1MetricResponseDataInnerDataPointsValues {
    'crashCount'?: number;
    'sessionCount'?: number;
    'feedbackCount'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "crashCount",
            "baseName": "crashCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "sessionCount",
            "baseName": "sessionCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "feedbackCount",
            "baseName": "feedbackCount",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppsBetaTesterUsagesV1MetricResponseDataInnerDataPointsValues.attributeTypeMap;
    }

    public constructor() {
    }
}

