/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment } from '../models/AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment.ts';
import { AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentTreatmentLocalizations } from '../models/AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentTreatmentLocalizations.ts';
import { HttpFile } from '../http/http.ts';

export class AppStoreVersionExperimentTreatmentRelationships {
    'appStoreVersionExperiment'?: AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment;
    'appStoreVersionExperimentV2'?: AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment;
    'appStoreVersionExperimentTreatmentLocalizations'?: AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentTreatmentLocalizations;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appStoreVersionExperiment",
            "baseName": "appStoreVersionExperiment",
            "type": "AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment",
            "format": ""
        },
        {
            "name": "appStoreVersionExperimentV2",
            "baseName": "appStoreVersionExperimentV2",
            "type": "AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperiment",
            "format": ""
        },
        {
            "name": "appStoreVersionExperimentTreatmentLocalizations",
            "baseName": "appStoreVersionExperimentTreatmentLocalizations",
            "type": "AppStoreVersionExperimentTreatmentRelationshipsAppStoreVersionExperimentTreatmentLocalizations",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionExperimentTreatmentRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

