/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppMediaAssetState } from '../models/AppMediaAssetState.ts';
import { UploadOperation } from '../models/UploadOperation.ts';
import { HttpFile } from '../http/http.ts';

export class AppStoreReviewAttachmentAttributes {
    'fileSize'?: number;
    'fileName'?: string;
    'sourceFileChecksum'?: string;
    'uploadOperations'?: Array<UploadOperation>;
    'assetDeliveryState'?: AppMediaAssetState;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fileSize",
            "baseName": "fileSize",
            "type": "number",
            "format": ""
        },
        {
            "name": "fileName",
            "baseName": "fileName",
            "type": "string",
            "format": ""
        },
        {
            "name": "sourceFileChecksum",
            "baseName": "sourceFileChecksum",
            "type": "string",
            "format": ""
        },
        {
            "name": "uploadOperations",
            "baseName": "uploadOperations",
            "type": "Array<UploadOperation>",
            "format": ""
        },
        {
            "name": "assetDeliveryState",
            "baseName": "assetDeliveryState",
            "type": "AppMediaAssetState",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppStoreReviewAttachmentAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}

