/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters } from '../models/AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters.ts';
import { HttpFile } from '../http/http.ts';

export class AppsBetaTesterUsagesV1MetricResponseDataInnerDimensions {
    'betaTesters'?: AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "betaTesters",
            "baseName": "betaTesters",
            "type": "AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTesters",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppsBetaTesterUsagesV1MetricResponseDataInnerDimensions.attributeTypeMap;
    }

    public constructor() {
    }
}

