/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppStoreVersionCreateRequestDataAttributes } from '../models/AppStoreVersionCreateRequestDataAttributes.ts';
import { AppStoreVersionCreateRequestDataRelationships } from '../models/AppStoreVersionCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class AppStoreVersionCreateRequestData {
    'type': AppStoreVersionCreateRequestDataTypeEnum;
    'attributes': AppStoreVersionCreateRequestDataAttributes;
    'relationships': AppStoreVersionCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppStoreVersionCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppStoreVersionCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppStoreVersionCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppStoreVersionCreateRequestDataTypeEnum {
    AppStoreVersions = 'appStoreVersions'
}

