/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion } from '../models/AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion.ts';
import { AppStoreVersionExperimentV2RelationshipsAppStoreVersionExperimentTreatments } from '../models/AppStoreVersionExperimentV2RelationshipsAppStoreVersionExperimentTreatments.ts';
import { HttpFile } from '../http/http.ts';

export class AppStoreVersionExperimentRelationships {
    'appStoreVersion'?: AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion;
    'appStoreVersionExperimentTreatments'?: AppStoreVersionExperimentV2RelationshipsAppStoreVersionExperimentTreatments;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "appStoreVersion",
            "baseName": "appStoreVersion",
            "type": "AppClipDefaultExperienceRelationshipsReleaseWithAppStoreVersion",
            "format": ""
        },
        {
            "name": "appStoreVersionExperimentTreatments",
            "baseName": "appStoreVersionExperimentTreatments",
            "type": "AppStoreVersionExperimentV2RelationshipsAppStoreVersionExperimentTreatments",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionExperimentRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

