/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppStoreVersionExperiment } from '../models/AppStoreVersionExperiment.ts';
import { AppStoreVersionExperimentTreatmentLocalization } from '../models/AppStoreVersionExperimentTreatmentLocalization.ts';
import { AppStoreVersionExperimentTreatmentLocalizationAttributes } from '../models/AppStoreVersionExperimentTreatmentLocalizationAttributes.ts';
import { AppStoreVersionExperimentTreatmentLocalizationRelationships } from '../models/AppStoreVersionExperimentTreatmentLocalizationRelationships.ts';
import { AppStoreVersionExperimentV2 } from '../models/AppStoreVersionExperimentV2.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { HttpFile } from '../http/http.ts';

export class AppStoreVersionExperimentTreatmentsResponseIncludedInner {
    'type': AppStoreVersionExperimentTreatmentsResponseIncludedInnerTypeEnum;
    'id': string;
    'attributes'?: AppStoreVersionExperimentTreatmentLocalizationAttributes;
    'relationships'?: AppStoreVersionExperimentTreatmentLocalizationRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppStoreVersionExperimentTreatmentsResponseIncludedInnerTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppStoreVersionExperimentTreatmentLocalizationAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppStoreVersionExperimentTreatmentLocalizationRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionExperimentTreatmentsResponseIncludedInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppStoreVersionExperimentTreatmentsResponseIncludedInnerTypeEnum {
    AppStoreVersionExperiments = 'appStoreVersionExperiments',
    AppStoreVersionExperimentTreatmentLocalizations = 'appStoreVersionExperimentTreatmentLocalizations'
}

