/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppStoreVersionPromotionCreateRequestDataRelationships } from '../models/AppStoreVersionPromotionCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class AppStoreVersionPromotionCreateRequestData {
    'type': AppStoreVersionPromotionCreateRequestDataTypeEnum;
    'relationships': AppStoreVersionPromotionCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppStoreVersionPromotionCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppStoreVersionPromotionCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppStoreVersionPromotionCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppStoreVersionPromotionCreateRequestDataTypeEnum {
    AppStoreVersionPromotions = 'appStoreVersionPromotions'
}

