/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppUpdateRequestDataRelationshipsAvailableTerritories } from '../models/AppUpdateRequestDataRelationshipsAvailableTerritories.ts';
import { AppUpdateRequestDataRelationshipsPrices } from '../models/AppUpdateRequestDataRelationshipsPrices.ts';
import { HttpFile } from '../http/http.ts';

export class AppUpdateRequestDataRelationships {
    'prices'?: AppUpdateRequestDataRelationshipsPrices;
    'availableTerritories'?: AppUpdateRequestDataRelationshipsAvailableTerritories;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "prices",
            "baseName": "prices",
            "type": "AppUpdateRequestDataRelationshipsPrices",
            "format": ""
        },
        {
            "name": "availableTerritories",
            "baseName": "availableTerritories",
            "type": "AppUpdateRequestDataRelationshipsAvailableTerritories",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppUpdateRequestDataRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

