/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppUpdateRequestDataAttributes } from '../models/AppUpdateRequestDataAttributes.ts';
import { AppUpdateRequestDataRelationships } from '../models/AppUpdateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class AppUpdateRequestData {
    'type': AppUpdateRequestDataTypeEnum;
    'id': string;
    'attributes'?: AppUpdateRequestDataAttributes;
    'relationships'?: AppUpdateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "AppUpdateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppUpdateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "AppUpdateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AppUpdateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum AppUpdateRequestDataTypeEnum {
    Apps = 'apps'
}

