/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BetaAppClipInvocationCreateRequestDataAttributes } from '../models/BetaAppClipInvocationCreateRequestDataAttributes.ts';
import { BetaAppClipInvocationCreateRequestDataRelationships } from '../models/BetaAppClipInvocationCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class BetaAppClipInvocationCreateRequestData {
    'type': BetaAppClipInvocationCreateRequestDataTypeEnum;
    'attributes': BetaAppClipInvocationCreateRequestDataAttributes;
    'relationships': BetaAppClipInvocationCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "BetaAppClipInvocationCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "BetaAppClipInvocationCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "BetaAppClipInvocationCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BetaAppClipInvocationCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum BetaAppClipInvocationCreateRequestDataTypeEnum {
    BetaAppClipInvocations = 'betaAppClipInvocations'
}

