/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BetaAppClipInvocationCreateRequestDataRelationshipsBetaAppClipInvocationLocalizations } from '../models/BetaAppClipInvocationCreateRequestDataRelationshipsBetaAppClipInvocationLocalizations.ts';
import { BetaAppClipInvocationCreateRequestDataRelationshipsBuildBundle } from '../models/BetaAppClipInvocationCreateRequestDataRelationshipsBuildBundle.ts';
import { HttpFile } from '../http/http.ts';

export class BetaAppClipInvocationCreateRequestDataRelationships {
    'buildBundle': BetaAppClipInvocationCreateRequestDataRelationshipsBuildBundle;
    'betaAppClipInvocationLocalizations': BetaAppClipInvocationCreateRequestDataRelationshipsBetaAppClipInvocationLocalizations;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "buildBundle",
            "baseName": "buildBundle",
            "type": "BetaAppClipInvocationCreateRequestDataRelationshipsBuildBundle",
            "format": ""
        },
        {
            "name": "betaAppClipInvocationLocalizations",
            "baseName": "betaAppClipInvocationLocalizations",
            "type": "BetaAppClipInvocationCreateRequestDataRelationshipsBetaAppClipInvocationLocalizations",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BetaAppClipInvocationCreateRequestDataRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

