/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BuildUpdateRequestDataAttributes } from '../models/BuildUpdateRequestDataAttributes.ts';
import { BuildUpdateRequestDataRelationships } from '../models/BuildUpdateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class BuildUpdateRequestData {
    'type': BuildUpdateRequestDataTypeEnum;
    'id': string;
    'attributes'?: BuildUpdateRequestDataAttributes;
    'relationships'?: BuildUpdateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "BuildUpdateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "BuildUpdateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "BuildUpdateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BuildUpdateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum BuildUpdateRequestDataTypeEnum {
    Builds = 'builds'
}

