/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BundleIdCapabilityCreateRequestDataAttributes } from '../models/BundleIdCapabilityCreateRequestDataAttributes.ts';
import { BundleIdCapabilityCreateRequestDataRelationships } from '../models/BundleIdCapabilityCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class BundleIdCapabilityCreateRequestData {
    'type': BundleIdCapabilityCreateRequestDataTypeEnum;
    'attributes': BundleIdCapabilityCreateRequestDataAttributes;
    'relationships': BundleIdCapabilityCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "BundleIdCapabilityCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "BundleIdCapabilityCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "BundleIdCapabilityCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BundleIdCapabilityCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum BundleIdCapabilityCreateRequestDataTypeEnum {
    BundleIdCapabilities = 'bundleIdCapabilities'
}

