/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CapabilityOption } from '../models/CapabilityOption.ts';
import { HttpFile } from '../http/http.ts';

export class CapabilitySetting {
    'key'?: CapabilitySettingKeyEnum;
    'name'?: string;
    'description'?: string;
    'enabledByDefault'?: boolean;
    'visible'?: boolean;
    'allowedInstances'?: CapabilitySettingAllowedInstancesEnum;
    'minInstances'?: number;
    'options'?: Array<CapabilityOption>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "CapabilitySettingKeyEnum",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabledByDefault",
            "baseName": "enabledByDefault",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "visible",
            "baseName": "visible",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "allowedInstances",
            "baseName": "allowedInstances",
            "type": "CapabilitySettingAllowedInstancesEnum",
            "format": ""
        },
        {
            "name": "minInstances",
            "baseName": "minInstances",
            "type": "number",
            "format": ""
        },
        {
            "name": "options",
            "baseName": "options",
            "type": "Array<CapabilityOption>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CapabilitySetting.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CapabilitySettingKeyEnum {
    IcloudVersion = 'ICLOUD_VERSION',
    DataProtectionPermissionLevel = 'DATA_PROTECTION_PERMISSION_LEVEL',
    AppleIdAuthAppConsent = 'APPLE_ID_AUTH_APP_CONSENT'
}
export enum CapabilitySettingAllowedInstancesEnum {
    Entry = 'ENTRY',
    Single = 'SINGLE',
    Multiple = 'MULTIPLE'
}

