/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BundleIdPlatform } from '../models/BundleIdPlatform.ts';
import { CertificateType } from '../models/CertificateType.ts';
import { HttpFile } from '../http/http.ts';

export class CertificateAttributes {
    'name'?: string;
    'certificateType'?: CertificateType;
    'displayName'?: string;
    'serialNumber'?: string;
    'platform'?: BundleIdPlatform;
    'expirationDate'?: Date;
    'certificateContent'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "certificateType",
            "baseName": "certificateType",
            "type": "CertificateType",
            "format": ""
        },
        {
            "name": "displayName",
            "baseName": "displayName",
            "type": "string",
            "format": ""
        },
        {
            "name": "serialNumber",
            "baseName": "serialNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "BundleIdPlatform",
            "format": ""
        },
        {
            "name": "expirationDate",
            "baseName": "expirationDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "certificateContent",
            "baseName": "certificateContent",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CertificateAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}



