/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BuildAudienceType } from '../models/BuildAudienceType.ts';
import { CiActionTestConfiguration } from '../models/CiActionTestConfiguration.ts';
import { CiActionType } from '../models/CiActionType.ts';
import { HttpFile } from '../http/http.ts';

export class CiAction {
    'name'?: string;
    'actionType'?: CiActionType;
    'destination'?: CiActionDestinationEnum;
    'buildDistributionAudience'?: BuildAudienceType;
    'testConfiguration'?: CiActionTestConfiguration;
    'scheme'?: string;
    'platform'?: CiActionPlatformEnum;
    'isRequiredToPass'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "actionType",
            "baseName": "actionType",
            "type": "CiActionType",
            "format": ""
        },
        {
            "name": "destination",
            "baseName": "destination",
            "type": "CiActionDestinationEnum",
            "format": ""
        },
        {
            "name": "buildDistributionAudience",
            "baseName": "buildDistributionAudience",
            "type": "BuildAudienceType",
            "format": ""
        },
        {
            "name": "testConfiguration",
            "baseName": "testConfiguration",
            "type": "CiActionTestConfiguration",
            "format": ""
        },
        {
            "name": "scheme",
            "baseName": "scheme",
            "type": "string",
            "format": ""
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "CiActionPlatformEnum",
            "format": ""
        },
        {
            "name": "isRequiredToPass",
            "baseName": "isRequiredToPass",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CiAction.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CiActionDestinationEnum {
    IosDevice = 'ANY_IOS_DEVICE',
    IosSimulator = 'ANY_IOS_SIMULATOR',
    TvosDevice = 'ANY_TVOS_DEVICE',
    TvosSimulator = 'ANY_TVOS_SIMULATOR',
    WatchosDevice = 'ANY_WATCHOS_DEVICE',
    WatchosSimulator = 'ANY_WATCHOS_SIMULATOR',
    Mac = 'ANY_MAC',
    MacCatalyst = 'ANY_MAC_CATALYST',
    VisionosDevice = 'ANY_VISIONOS_DEVICE',
    VisionosSimulator = 'ANY_VISIONOS_SIMULATOR'
}
export enum CiActionPlatformEnum {
    Macos = 'MACOS',
    Ios = 'IOS',
    Tvos = 'TVOS',
    Watchos = 'WATCHOS',
    Visionos = 'VISIONOS'
}

