/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CiStartConditionFileMatcher } from '../models/CiStartConditionFileMatcher.ts';
import { HttpFile } from '../http/http.ts';

export class CiFilesAndFoldersRule {
    'mode'?: CiFilesAndFoldersRuleModeEnum;
    'matchers'?: Array<CiStartConditionFileMatcher>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "mode",
            "baseName": "mode",
            "type": "CiFilesAndFoldersRuleModeEnum",
            "format": ""
        },
        {
            "name": "matchers",
            "baseName": "matchers",
            "type": "Array<CiStartConditionFileMatcher>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CiFilesAndFoldersRule.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CiFilesAndFoldersRuleModeEnum {
    StartIfAnyFileMatches = 'START_IF_ANY_FILE_MATCHES',
    DoNotStartIfAllFilesMatch = 'DO_NOT_START_IF_ALL_FILES_MATCH'
}

