/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class CiScheduledStartConditionSchedule {
    'frequency'?: CiScheduledStartConditionScheduleFrequencyEnum;
    'days'?: Array<CiScheduledStartConditionScheduleDaysEnum>;
    'hour'?: number;
    'minute'?: number;
    'timezone'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "frequency",
            "baseName": "frequency",
            "type": "CiScheduledStartConditionScheduleFrequencyEnum",
            "format": ""
        },
        {
            "name": "days",
            "baseName": "days",
            "type": "Array<CiScheduledStartConditionScheduleDaysEnum>",
            "format": ""
        },
        {
            "name": "hour",
            "baseName": "hour",
            "type": "number",
            "format": ""
        },
        {
            "name": "minute",
            "baseName": "minute",
            "type": "number",
            "format": ""
        },
        {
            "name": "timezone",
            "baseName": "timezone",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CiScheduledStartConditionSchedule.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CiScheduledStartConditionScheduleFrequencyEnum {
    Weekly = 'WEEKLY',
    Daily = 'DAILY',
    Hourly = 'HOURLY'
}
export enum CiScheduledStartConditionScheduleDaysEnum {
    Sunday = 'SUNDAY',
    Monday = 'MONDAY',
    Tuesday = 'TUESDAY',
    Wednesday = 'WEDNESDAY',
    Thursday = 'THURSDAY',
    Friday = 'FRIDAY',
    Saturday = 'SATURDAY'
}

