/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CiTestResultAttributesDestinationTestResultsInner } from '../models/CiTestResultAttributesDestinationTestResultsInner.ts';
import { CiTestStatus } from '../models/CiTestStatus.ts';
import { FileLocation } from '../models/FileLocation.ts';
import { HttpFile } from '../http/http.ts';

export class CiTestResultAttributes {
    'className'?: string;
    'name'?: string;
    'status'?: CiTestStatus;
    'fileSource'?: FileLocation;
    'message'?: string;
    'destinationTestResults'?: Array<CiTestResultAttributesDestinationTestResultsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "className",
            "baseName": "className",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CiTestStatus",
            "format": ""
        },
        {
            "name": "fileSource",
            "baseName": "fileSource",
            "type": "FileLocation",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "destinationTestResults",
            "baseName": "destinationTestResults",
            "type": "Array<CiTestResultAttributesDestinationTestResultsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CiTestResultAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}



