/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CiWorkflowCreateRequestDataRelationshipsMacOsVersion } from '../models/CiWorkflowCreateRequestDataRelationshipsMacOsVersion.ts';
import { CiWorkflowCreateRequestDataRelationshipsProduct } from '../models/CiWorkflowCreateRequestDataRelationshipsProduct.ts';
import { CiWorkflowCreateRequestDataRelationshipsRepository } from '../models/CiWorkflowCreateRequestDataRelationshipsRepository.ts';
import { CiWorkflowCreateRequestDataRelationshipsXcodeVersion } from '../models/CiWorkflowCreateRequestDataRelationshipsXcodeVersion.ts';
import { HttpFile } from '../http/http.ts';

export class CiWorkflowCreateRequestDataRelationships {
    'product': CiWorkflowCreateRequestDataRelationshipsProduct;
    'repository': CiWorkflowCreateRequestDataRelationshipsRepository;
    'xcodeVersion': CiWorkflowCreateRequestDataRelationshipsXcodeVersion;
    'macOsVersion': CiWorkflowCreateRequestDataRelationshipsMacOsVersion;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "product",
            "baseName": "product",
            "type": "CiWorkflowCreateRequestDataRelationshipsProduct",
            "format": ""
        },
        {
            "name": "repository",
            "baseName": "repository",
            "type": "CiWorkflowCreateRequestDataRelationshipsRepository",
            "format": ""
        },
        {
            "name": "xcodeVersion",
            "baseName": "xcodeVersion",
            "type": "CiWorkflowCreateRequestDataRelationshipsXcodeVersion",
            "format": ""
        },
        {
            "name": "macOsVersion",
            "baseName": "macOsVersion",
            "type": "CiWorkflowCreateRequestDataRelationshipsMacOsVersion",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CiWorkflowCreateRequestDataRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

