/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CiXcodeVersionAttributesTestDestinationsInner } from '../models/CiXcodeVersionAttributesTestDestinationsInner.ts';
import { HttpFile } from '../http/http.ts';

export class CiXcodeVersionAttributes {
    'version'?: string;
    'name'?: string;
    'testDestinations'?: Array<CiXcodeVersionAttributesTestDestinationsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "testDestinations",
            "baseName": "testDestinations",
            "type": "Array<CiXcodeVersionAttributesTestDestinationsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CiXcodeVersionAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}

