/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CustomerReviewResponseV1CreateRequestDataRelationshipsReview } from '../models/CustomerReviewResponseV1CreateRequestDataRelationshipsReview.ts';
import { HttpFile } from '../http/http.ts';

export class CustomerReviewResponseV1CreateRequestDataRelationships {
    'review': CustomerReviewResponseV1CreateRequestDataRelationshipsReview;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "review",
            "baseName": "review",
            "type": "CustomerReviewResponseV1CreateRequestDataRelationshipsReview",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CustomerReviewResponseV1CreateRequestDataRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

