/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class DiagnosticLogsProductDataInnerDiagnosticInsightsInner {
    'insightsURL'?: string;
    'insightsCategory'?: string;
    'insightsString'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "insightsURL",
            "baseName": "insightsURL",
            "type": "string",
            "format": ""
        },
        {
            "name": "insightsCategory",
            "baseName": "insightsCategory",
            "type": "string",
            "format": ""
        },
        {
            "name": "insightsString",
            "baseName": "insightsString",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DiagnosticLogsProductDataInnerDiagnosticInsightsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

