/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner } from '../models/DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner.ts';
import { DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData } from '../models/DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData.ts';
import { HttpFile } from '../http/http.ts';

export class DiagnosticLogsProductDataInnerDiagnosticLogsInner {
    'callStackTree'?: Array<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner>;
    'diagnosticMetaData'?: DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "callStackTree",
            "baseName": "callStackTree",
            "type": "Array<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner>",
            "format": ""
        },
        {
            "name": "diagnosticMetaData",
            "baseName": "diagnosticMetaData",
            "type": "DiagnosticLogsProductDataInnerDiagnosticLogsInnerDiagnosticMetaData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DiagnosticLogsProductDataInnerDiagnosticLogsInner.attributeTypeMap;
    }

    public constructor() {
    }
}

