/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner } from '../models/DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner.ts';
import { HttpFile } from '../http/http.ts';

export class DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner {
    'callStackPerThread'?: boolean;
    'callStacks'?: Array<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "callStackPerThread",
            "baseName": "callStackPerThread",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "callStacks",
            "baseName": "callStacks",
            "type": "Array<DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInnerCallStacksInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DiagnosticLogsProductDataInnerDiagnosticLogsInnerCallStackTreeInner.attributeTypeMap;
    }

    public constructor() {
    }
}

