/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EndUserLicenseAgreementCreateRequestDataAttributes } from '../models/EndUserLicenseAgreementCreateRequestDataAttributes.ts';
import { EndUserLicenseAgreementCreateRequestDataRelationships } from '../models/EndUserLicenseAgreementCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class EndUserLicenseAgreementCreateRequestData {
    'type': EndUserLicenseAgreementCreateRequestDataTypeEnum;
    'attributes': EndUserLicenseAgreementCreateRequestDataAttributes;
    'relationships': EndUserLicenseAgreementCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "EndUserLicenseAgreementCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "EndUserLicenseAgreementCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "EndUserLicenseAgreementCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return EndUserLicenseAgreementCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum EndUserLicenseAgreementCreateRequestDataTypeEnum {
    EndUserLicenseAgreements = 'endUserLicenseAgreements'
}

