/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ImageAsset } from '../models/ImageAsset.ts';
import { Platform } from '../models/Platform.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterEnabledVersionAttributes {
    'platform'?: Platform;
    'versionString'?: string;
    'iconAsset'?: ImageAsset;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "platform",
            "baseName": "platform",
            "type": "Platform",
            "format": ""
        },
        {
            "name": "versionString",
            "baseName": "versionString",
            "type": "string",
            "format": ""
        },
        {
            "name": "iconAsset",
            "baseName": "iconAsset",
            "type": "ImageAsset",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterEnabledVersionAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}



