/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterAchievementLocalizationCreateRequestDataAttributes } from '../models/GameCenterAchievementLocalizationCreateRequestDataAttributes.ts';
import { GameCenterAchievementLocalizationCreateRequestDataRelationships } from '../models/GameCenterAchievementLocalizationCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterAchievementLocalizationCreateRequestData {
    'type': GameCenterAchievementLocalizationCreateRequestDataTypeEnum;
    'attributes': GameCenterAchievementLocalizationCreateRequestDataAttributes;
    'relationships': GameCenterAchievementLocalizationCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GameCenterAchievementLocalizationCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "GameCenterAchievementLocalizationCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GameCenterAchievementLocalizationCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterAchievementLocalizationCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GameCenterAchievementLocalizationCreateRequestDataTypeEnum {
    GameCenterAchievementLocalizations = 'gameCenterAchievementLocalizations'
}

