/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterAchievement } from '../models/GameCenterAchievement.ts';
import { GameCenterAchievementLocalization } from '../models/GameCenterAchievementLocalization.ts';
import { GameCenterAchievementRelease } from '../models/GameCenterAchievementRelease.ts';
import { GameCenterAchievementReleaseAttributes } from '../models/GameCenterAchievementReleaseAttributes.ts';
import { GameCenterAchievementReleaseRelationships } from '../models/GameCenterAchievementReleaseRelationships.ts';
import { GameCenterDetail } from '../models/GameCenterDetail.ts';
import { GameCenterGroup } from '../models/GameCenterGroup.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterAchievementsResponseIncludedInner {
    'type': GameCenterAchievementsResponseIncludedInnerTypeEnum;
    'id': string;
    'attributes'?: GameCenterAchievementReleaseAttributes;
    'relationships'?: GameCenterAchievementReleaseRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GameCenterAchievementsResponseIncludedInnerTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "GameCenterAchievementReleaseAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GameCenterAchievementReleaseRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterAchievementsResponseIncludedInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GameCenterAchievementsResponseIncludedInnerTypeEnum {
    GameCenterDetails = 'gameCenterDetails',
    GameCenterGroups = 'gameCenterGroups',
    GameCenterAchievements = 'gameCenterAchievements',
    GameCenterAchievementLocalizations = 'gameCenterAchievementLocalizations',
    GameCenterAchievementReleases = 'gameCenterAchievementReleases'
}

