/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement } from '../models/GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement.ts';
import { GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail } from '../models/GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterAchievementReleaseCreateRequestDataRelationships {
    'gameCenterDetail': GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail;
    'gameCenterAchievement': GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "gameCenterDetail",
            "baseName": "gameCenterDetail",
            "type": "GameCenterAchievementReleaseCreateRequestDataRelationshipsGameCenterDetail",
            "format": ""
        },
        {
            "name": "gameCenterAchievement",
            "baseName": "gameCenterAchievement",
            "type": "GameCenterAchievementLocalizationCreateRequestDataRelationshipsGameCenterAchievement",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterAchievementReleaseCreateRequestDataRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

