/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Property } from '../models/Property.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes {
    'playerId': string;
    'properties'?: Array<Property>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "playerId",
            "baseName": "playerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Array<Property>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterMatchmakingTestPlayerPropertyInlineCreateAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}

