/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterEnabledVersionAttributes } from '../models/GameCenterEnabledVersionAttributes.ts';
import { GameCenterEnabledVersionRelationships } from '../models/GameCenterEnabledVersionRelationships.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterEnabledVersion {
    'type': GameCenterEnabledVersionTypeEnum;
    'id': string;
    'attributes'?: GameCenterEnabledVersionAttributes;
    'relationships'?: GameCenterEnabledVersionRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GameCenterEnabledVersionTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "GameCenterEnabledVersionAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GameCenterEnabledVersionRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterEnabledVersion.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GameCenterEnabledVersionTypeEnum {
    GameCenterEnabledVersions = 'gameCenterEnabledVersions'
}

