/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterAchievementLocalizationAttributes } from '../models/GameCenterAchievementLocalizationAttributes.ts';
import { GameCenterAchievementLocalizationRelationships } from '../models/GameCenterAchievementLocalizationRelationships.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterAchievementLocalization {
    'type': GameCenterAchievementLocalizationTypeEnum;
    'id': string;
    'attributes'?: GameCenterAchievementLocalizationAttributes;
    'relationships'?: GameCenterAchievementLocalizationRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GameCenterAchievementLocalizationTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "GameCenterAchievementLocalizationAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GameCenterAchievementLocalizationRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterAchievementLocalization.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GameCenterAchievementLocalizationTypeEnum {
    GameCenterAchievementLocalizations = 'gameCenterAchievementLocalizations'
}

