/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterLeaderboardSetReleaseCreateRequestDataRelationships } from '../models/GameCenterLeaderboardSetReleaseCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterLeaderboardSetReleaseCreateRequestData {
    'type': GameCenterLeaderboardSetReleaseCreateRequestDataTypeEnum;
    'relationships': GameCenterLeaderboardSetReleaseCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GameCenterLeaderboardSetReleaseCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GameCenterLeaderboardSetReleaseCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterLeaderboardSetReleaseCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GameCenterLeaderboardSetReleaseCreateRequestDataTypeEnum {
    GameCenterLeaderboardSetReleases = 'gameCenterLeaderboardSetReleases'
}

