/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterGroupAttributes } from '../models/GameCenterGroupAttributes.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterGroupCreateRequestData {
    'type': GameCenterGroupCreateRequestDataTypeEnum;
    'attributes'?: GameCenterGroupAttributes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GameCenterGroupCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "GameCenterGroupAttributes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterGroupCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GameCenterGroupCreateRequestDataTypeEnum {
    GameCenterGroups = 'gameCenterGroups'
}

