/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipAdvancedExperienceImageCreateRequestDataAttributes } from '../models/AppClipAdvancedExperienceImageCreateRequestDataAttributes.ts';
import { GameCenterAchievementImageCreateRequestDataRelationships } from '../models/GameCenterAchievementImageCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterAchievementImageCreateRequestData {
    'type': GameCenterAchievementImageCreateRequestDataTypeEnum;
    'attributes': AppClipAdvancedExperienceImageCreateRequestDataAttributes;
    'relationships': GameCenterAchievementImageCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GameCenterAchievementImageCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppClipAdvancedExperienceImageCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GameCenterAchievementImageCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterAchievementImageCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GameCenterAchievementImageCreateRequestDataTypeEnum {
    GameCenterAchievementImages = 'gameCenterAchievementImages'
}

