/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterLeaderboardLocalizationCreateRequestDataAttributes } from '../models/GameCenterLeaderboardLocalizationCreateRequestDataAttributes.ts';
import { GameCenterLeaderboardLocalizationCreateRequestDataRelationships } from '../models/GameCenterLeaderboardLocalizationCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterLeaderboardLocalizationCreateRequestData {
    'type': GameCenterLeaderboardLocalizationCreateRequestDataTypeEnum;
    'attributes': GameCenterLeaderboardLocalizationCreateRequestDataAttributes;
    'relationships': GameCenterLeaderboardLocalizationCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GameCenterLeaderboardLocalizationCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "GameCenterLeaderboardLocalizationCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GameCenterLeaderboardLocalizationCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterLeaderboardLocalizationCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GameCenterLeaderboardLocalizationCreateRequestDataTypeEnum {
    GameCenterLeaderboardLocalizations = 'gameCenterLeaderboardLocalizations'
}

