/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueues } from '../models/GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueues.ts';
import { GameCenterMatchmakingRuleSetRelationshipsRules } from '../models/GameCenterMatchmakingRuleSetRelationshipsRules.ts';
import { GameCenterMatchmakingRuleSetRelationshipsTeams } from '../models/GameCenterMatchmakingRuleSetRelationshipsTeams.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterMatchmakingRuleSetRelationships {
    'teams'?: GameCenterMatchmakingRuleSetRelationshipsTeams;
    'rules'?: GameCenterMatchmakingRuleSetRelationshipsRules;
    'matchmakingQueues'?: GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueues;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "teams",
            "baseName": "teams",
            "type": "GameCenterMatchmakingRuleSetRelationshipsTeams",
            "format": ""
        },
        {
            "name": "rules",
            "baseName": "rules",
            "type": "GameCenterMatchmakingRuleSetRelationshipsRules",
            "format": ""
        },
        {
            "name": "matchmakingQueues",
            "baseName": "matchmakingQueues",
            "type": "GameCenterMatchmakingRuleSetRelationshipsMatchmakingQueues",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterMatchmakingRuleSetRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

