/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerDataPointsValues } from '../models/GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerDataPointsValues.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerDataPoints {
    'start'?: Date;
    'end'?: Date;
    'values'?: GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerDataPointsValues;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "start",
            "baseName": "start",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "end",
            "baseName": "end",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerDataPointsValues",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterMatchmakingBooleanRuleResultsV1MetricResponseDataInnerDataPoints.attributeTypeMap;
    }

    public constructor() {
    }
}

