/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Location } from '../models/Location.ts';
import { Platform } from '../models/Platform.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterMatchmakingTestRequestInlineCreateAttributes {
    'requestName': string;
    'secondsInQueue': number;
    'locale'?: GameCenterMatchmakingTestRequestInlineCreateAttributesLocaleEnum;
    'location'?: Location;
    'minPlayers'?: number;
    'maxPlayers'?: number;
    'playerCount'?: number;
    'bundleId': string;
    'platform': Platform;
    'appVersion': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "requestName",
            "baseName": "requestName",
            "type": "string",
            "format": ""
        },
        {
            "name": "secondsInQueue",
            "baseName": "secondsInQueue",
            "type": "number",
            "format": ""
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "GameCenterMatchmakingTestRequestInlineCreateAttributesLocaleEnum",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "Location",
            "format": ""
        },
        {
            "name": "minPlayers",
            "baseName": "minPlayers",
            "type": "number",
            "format": ""
        },
        {
            "name": "maxPlayers",
            "baseName": "maxPlayers",
            "type": "number",
            "format": ""
        },
        {
            "name": "playerCount",
            "baseName": "playerCount",
            "type": "number",
            "format": ""
        },
        {
            "name": "bundleId",
            "baseName": "bundleId",
            "type": "string",
            "format": ""
        },
        {
            "name": "platform",
            "baseName": "platform",
            "type": "Platform",
            "format": ""
        },
        {
            "name": "appVersion",
            "baseName": "appVersion",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterMatchmakingTestRequestInlineCreateAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GameCenterMatchmakingTestRequestInlineCreateAttributesLocaleEnum {
    ArSa = 'AR-SA',
    CaEs = 'CA-ES',
    CsCz = 'CS-CZ',
    DaDk = 'DA-DK',
    DeDe = 'DE-DE',
    ElGr = 'EL-GR',
    EnAu = 'EN-AU',
    EnGb = 'EN-GB',
    EnUs = 'EN-US',
    EnKy = 'EN-KY',
    EsEs = 'ES-ES',
    EsMx = 'ES-MX',
    FiFi = 'FI-FI',
    FrCa = 'FR-CA',
    FrFr = 'FR-FR',
    HiIn = 'HI-IN',
    HrHr = 'HR-HR',
    HuHu = 'HU-HU',
    IdId = 'ID-ID',
    ItIt = 'IT-IT',
    IwIl = 'IW-IL',
    JaJp = 'JA-JP',
    KoKr = 'KO-KR',
    MsMy = 'MS-MY',
    NlNl = 'NL-NL',
    NoNo = 'NO-NO',
    PlPl = 'PL-PL',
    PtBr = 'PT-BR',
    PtPt = 'PT-PT',
    RoRo = 'RO-RO',
    RuRu = 'RU-RU',
    SkSk = 'SK-SK',
    SvSe = 'SV-SE',
    ThTh = 'TH-TH',
    TrTr = 'TR-TR',
    UkUa = 'UK-UA',
    ZhCn = 'ZH-CN',
    ZhTw = 'ZH-TW',
    ZhHk = 'ZH-HK'
}

