/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterDetailRelationshipsDefaultLeaderboard } from '../models/GameCenterDetailRelationshipsDefaultLeaderboard.ts';
import { GameCenterLeaderboardLocalizationRelationshipsGameCenterLeaderboardImage } from '../models/GameCenterLeaderboardLocalizationRelationshipsGameCenterLeaderboardImage.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterLeaderboardLocalizationRelationships {
    'gameCenterLeaderboard'?: GameCenterDetailRelationshipsDefaultLeaderboard;
    'gameCenterLeaderboardImage'?: GameCenterLeaderboardLocalizationRelationshipsGameCenterLeaderboardImage;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "gameCenterLeaderboard",
            "baseName": "gameCenterLeaderboard",
            "type": "GameCenterDetailRelationshipsDefaultLeaderboard",
            "format": ""
        },
        {
            "name": "gameCenterLeaderboardImage",
            "baseName": "gameCenterLeaderboardImage",
            "type": "GameCenterLeaderboardLocalizationRelationshipsGameCenterLeaderboardImage",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterLeaderboardLocalizationRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

