/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterLeaderboard } from '../models/GameCenterLeaderboard.ts';
import { GameCenterLeaderboardAttributes } from '../models/GameCenterLeaderboardAttributes.ts';
import { GameCenterLeaderboardRelationships } from '../models/GameCenterLeaderboardRelationships.ts';
import { GameCenterLeaderboardSet } from '../models/GameCenterLeaderboardSet.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterLeaderboardSetMemberLocalizationsResponseIncludedInner {
    'type': GameCenterLeaderboardSetMemberLocalizationsResponseIncludedInnerTypeEnum;
    'id': string;
    'attributes'?: GameCenterLeaderboardAttributes;
    'relationships'?: GameCenterLeaderboardRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GameCenterLeaderboardSetMemberLocalizationsResponseIncludedInnerTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "GameCenterLeaderboardAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GameCenterLeaderboardRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterLeaderboardSetMemberLocalizationsResponseIncludedInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GameCenterLeaderboardSetMemberLocalizationsResponseIncludedInnerTypeEnum {
    GameCenterLeaderboardSets = 'gameCenterLeaderboardSets',
    GameCenterLeaderboards = 'gameCenterLeaderboards'
}

