/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterMatchmakingQueueRelationshipsRuleSet } from '../models/GameCenterMatchmakingQueueRelationshipsRuleSet.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterMatchmakingQueueRelationships {
    'ruleSet'?: GameCenterMatchmakingQueueRelationshipsRuleSet;
    'experimentRuleSet'?: GameCenterMatchmakingQueueRelationshipsRuleSet;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "ruleSet",
            "baseName": "ruleSet",
            "type": "GameCenterMatchmakingQueueRelationshipsRuleSet",
            "format": ""
        },
        {
            "name": "experimentRuleSet",
            "baseName": "experimentRuleSet",
            "type": "GameCenterMatchmakingQueueRelationshipsRuleSet",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterMatchmakingQueueRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

