/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GameCenterAchievementReleaseCreateRequestDataRelationships } from '../models/GameCenterAchievementReleaseCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class GameCenterAchievementReleaseCreateRequestData {
    'type': GameCenterAchievementReleaseCreateRequestDataTypeEnum;
    'relationships': GameCenterAchievementReleaseCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "GameCenterAchievementReleaseCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "GameCenterAchievementReleaseCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return GameCenterAchievementReleaseCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum GameCenterAchievementReleaseCreateRequestDataTypeEnum {
    GameCenterAchievementReleases = 'gameCenterAchievementReleases'
}

