/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppAvailabilityV2Attributes } from '../models/AppAvailabilityV2Attributes.ts';
import { InAppPurchaseAppStoreReviewScreenshot } from '../models/InAppPurchaseAppStoreReviewScreenshot.ts';
import { InAppPurchaseAvailability } from '../models/InAppPurchaseAvailability.ts';
import { InAppPurchaseAvailabilityRelationships } from '../models/InAppPurchaseAvailabilityRelationships.ts';
import { InAppPurchaseContent } from '../models/InAppPurchaseContent.ts';
import { InAppPurchaseLocalization } from '../models/InAppPurchaseLocalization.ts';
import { InAppPurchasePricePoint } from '../models/InAppPurchasePricePoint.ts';
import { InAppPurchasePriceSchedule } from '../models/InAppPurchasePriceSchedule.ts';
import { PromotedPurchase } from '../models/PromotedPurchase.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { HttpFile } from '../http/http.ts';

export class InAppPurchasesV2ResponseIncludedInner {
    'type': InAppPurchasesV2ResponseIncludedInnerTypeEnum;
    'id': string;
    'attributes'?: AppAvailabilityV2Attributes;
    'relationships'?: InAppPurchaseAvailabilityRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "InAppPurchasesV2ResponseIncludedInnerTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppAvailabilityV2Attributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "InAppPurchaseAvailabilityRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchasesV2ResponseIncludedInner.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum InAppPurchasesV2ResponseIncludedInnerTypeEnum {
    InAppPurchaseLocalizations = 'inAppPurchaseLocalizations',
    InAppPurchasePricePoints = 'inAppPurchasePricePoints',
    InAppPurchaseContents = 'inAppPurchaseContents',
    InAppPurchaseAppStoreReviewScreenshots = 'inAppPurchaseAppStoreReviewScreenshots',
    PromotedPurchases = 'promotedPurchases',
    InAppPurchasePriceSchedules = 'inAppPurchasePriceSchedules',
    InAppPurchaseAvailabilities = 'inAppPurchaseAvailabilities'
}

