/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class InAppPurchaseLocalizationAttributes {
    'name'?: string;
    'locale'?: string;
    'description'?: string;
    'state'?: InAppPurchaseLocalizationAttributesStateEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "locale",
            "baseName": "locale",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "InAppPurchaseLocalizationAttributesStateEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchaseLocalizationAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum InAppPurchaseLocalizationAttributesStateEnum {
    PrepareForSubmission = 'PREPARE_FOR_SUBMISSION',
    WaitingForReview = 'WAITING_FOR_REVIEW',
    Approved = 'APPROVED',
    Rejected = 'REJECTED'
}

