/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InAppPurchaseV2UpdateRequestDataAttributes } from '../models/InAppPurchaseV2UpdateRequestDataAttributes.ts';
import { HttpFile } from '../http/http.ts';

export class InAppPurchaseV2UpdateRequestData {
    'type': InAppPurchaseV2UpdateRequestDataTypeEnum;
    'id': string;
    'attributes'?: InAppPurchaseV2UpdateRequestDataAttributes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "InAppPurchaseV2UpdateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "InAppPurchaseV2UpdateRequestDataAttributes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchaseV2UpdateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum InAppPurchaseV2UpdateRequestDataTypeEnum {
    InAppPurchases = 'inAppPurchases'
}

