/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class InAppPurchasePricePointAttributes {
    'customerPrice'?: string;
    'proceeds'?: string;
    'priceTier'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "customerPrice",
            "baseName": "customerPrice",
            "type": "string",
            "format": ""
        },
        {
            "name": "proceeds",
            "baseName": "proceeds",
            "type": "string",
            "format": ""
        },
        {
            "name": "priceTier",
            "baseName": "priceTier",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchasePricePointAttributes.attributeTypeMap;
    }

    public constructor() {
    }
}

