/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2 } from '../models/InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2.ts';
import { HttpFile } from '../http/http.ts';

export class InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationships {
    'inAppPurchaseV2': InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "inAppPurchaseV2",
            "baseName": "inAppPurchaseV2",
            "type": "InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationshipsInAppPurchaseV2",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchaseAppStoreReviewScreenshotCreateRequestDataRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

