/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentLinks } from '../models/DocumentLinks.ts';
import { InAppPurchaseV2 } from '../models/InAppPurchaseV2.ts';
import { InAppPurchasesV2ResponseIncludedInner } from '../models/InAppPurchasesV2ResponseIncludedInner.ts';
import { HttpFile } from '../http/http.ts';

export class InAppPurchaseV2Response {
    'data': InAppPurchaseV2;
    'included'?: Array<InAppPurchasesV2ResponseIncludedInner>;
    'links': DocumentLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "InAppPurchaseV2",
            "format": ""
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<InAppPurchasesV2ResponseIncludedInner>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "DocumentLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InAppPurchaseV2Response.attributeTypeMap;
    }

    public constructor() {
    }
}

