/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PromotedPurchaseUpdateRequestDataAttributes } from '../models/PromotedPurchaseUpdateRequestDataAttributes.ts';
import { HttpFile } from '../http/http.ts';

export class PromotedPurchaseUpdateRequestData {
    'type': PromotedPurchaseUpdateRequestDataTypeEnum;
    'id': string;
    'attributes'?: PromotedPurchaseUpdateRequestDataAttributes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PromotedPurchaseUpdateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "PromotedPurchaseUpdateRequestDataAttributes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PromotedPurchaseUpdateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PromotedPurchaseUpdateRequestDataTypeEnum {
    PromotedPurchases = 'promotedPurchases'
}

