/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppClipAdvancedExperienceImageCreateRequestDataAttributes } from '../models/AppClipAdvancedExperienceImageCreateRequestDataAttributes.ts';
import { PromotedPurchaseImageCreateRequestDataRelationships } from '../models/PromotedPurchaseImageCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class PromotedPurchaseImageCreateRequestData {
    'type': PromotedPurchaseImageCreateRequestDataTypeEnum;
    'attributes': AppClipAdvancedExperienceImageCreateRequestDataAttributes;
    'relationships': PromotedPurchaseImageCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "PromotedPurchaseImageCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "AppClipAdvancedExperienceImageCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "PromotedPurchaseImageCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PromotedPurchaseImageCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum PromotedPurchaseImageCreateRequestDataTypeEnum {
    PromotedPurchaseImages = 'promotedPurchaseImages'
}

