/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PagedDocumentLinks } from '../models/PagedDocumentLinks.ts';
import { PagingInformation } from '../models/PagingInformation.ts';
import { ScmGitReference } from '../models/ScmGitReference.ts';
import { ScmRepository } from '../models/ScmRepository.ts';
import { HttpFile } from '../http/http.ts';

export class ScmGitReferencesResponse {
    'data': Array<ScmGitReference>;
    'included'?: Array<ScmRepository>;
    'links': PagedDocumentLinks;
    'meta'?: PagingInformation;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<ScmGitReference>",
            "format": ""
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<ScmRepository>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "PagedDocumentLinks",
            "format": ""
        },
        {
            "name": "meta",
            "baseName": "meta",
            "type": "PagingInformation",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ScmGitReferencesResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

