/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ResourceLinks } from '../models/ResourceLinks.ts';
import { ScmRepositoryAttributes } from '../models/ScmRepositoryAttributes.ts';
import { ScmRepositoryRelationships } from '../models/ScmRepositoryRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class ScmRepository {
    'type': ScmRepositoryTypeEnum;
    'id': string;
    'attributes'?: ScmRepositoryAttributes;
    'relationships'?: ScmRepositoryRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "ScmRepositoryTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "ScmRepositoryAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "ScmRepositoryRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ScmRepository.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ScmRepositoryTypeEnum {
    ScmRepositories = 'scmRepositories'
}

