/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InAppPurchasePricePointRelationships } from '../models/InAppPurchasePricePointRelationships.ts';
import { ResourceLinks } from '../models/ResourceLinks.ts';
import { SubscriptionPricePointAttributes } from '../models/SubscriptionPricePointAttributes.ts';
import { HttpFile } from '../http/http.ts';

export class SubscriptionPricePoint {
    'type': SubscriptionPricePointTypeEnum;
    'id': string;
    'attributes'?: SubscriptionPricePointAttributes;
    'relationships'?: InAppPurchasePricePointRelationships;
    'links'?: ResourceLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SubscriptionPricePointTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "SubscriptionPricePointAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "InAppPurchasePricePointRelationships",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "ResourceLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionPricePoint.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SubscriptionPricePointTypeEnum {
    SubscriptionPricePoints = 'subscriptionPricePoints'
}

