/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppPricePointV2RelationshipsTerritory } from '../models/AppPricePointV2RelationshipsTerritory.ts';
import { PromotedPurchaseRelationshipsSubscription } from '../models/PromotedPurchaseRelationshipsSubscription.ts';
import { SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePoint } from '../models/SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePoint.ts';
import { HttpFile } from '../http/http.ts';

export class SubscriptionIntroductoryOfferRelationships {
    'subscription'?: PromotedPurchaseRelationshipsSubscription;
    'territory'?: AppPricePointV2RelationshipsTerritory;
    'subscriptionPricePoint'?: SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePoint;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "PromotedPurchaseRelationshipsSubscription",
            "format": ""
        },
        {
            "name": "territory",
            "baseName": "territory",
            "type": "AppPricePointV2RelationshipsTerritory",
            "format": ""
        },
        {
            "name": "subscriptionPricePoint",
            "baseName": "subscriptionPricePoint",
            "type": "SubscriptionIntroductoryOfferRelationshipsSubscriptionPricePoint",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionIntroductoryOfferRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

