/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubscriptionPromotionalOfferCreateRequestDataRelationships } from '../models/SubscriptionPromotionalOfferCreateRequestDataRelationships.ts';
import { SubscriptionPromotionalOfferInlineCreateAttributes } from '../models/SubscriptionPromotionalOfferInlineCreateAttributes.ts';
import { HttpFile } from '../http/http.ts';

export class SubscriptionPromotionalOfferCreateRequestData {
    'type': SubscriptionPromotionalOfferCreateRequestDataTypeEnum;
    'attributes': SubscriptionPromotionalOfferInlineCreateAttributes;
    'relationships': SubscriptionPromotionalOfferCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SubscriptionPromotionalOfferCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "SubscriptionPromotionalOfferInlineCreateAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "SubscriptionPromotionalOfferCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionPromotionalOfferCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SubscriptionPromotionalOfferCreateRequestDataTypeEnum {
    SubscriptionPromotionalOffers = 'subscriptionPromotionalOffers'
}

