/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { InAppPurchaseV2RelationshipsPromotedPurchase } from '../models/InAppPurchaseV2RelationshipsPromotedPurchase.ts';
import { SubscriptionGroupLocalizationRelationshipsSubscriptionGroup } from '../models/SubscriptionGroupLocalizationRelationshipsSubscriptionGroup.ts';
import { SubscriptionRelationshipsAppStoreReviewScreenshot } from '../models/SubscriptionRelationshipsAppStoreReviewScreenshot.ts';
import { SubscriptionRelationshipsIntroductoryOffers } from '../models/SubscriptionRelationshipsIntroductoryOffers.ts';
import { SubscriptionRelationshipsOfferCodes } from '../models/SubscriptionRelationshipsOfferCodes.ts';
import { SubscriptionRelationshipsPrices } from '../models/SubscriptionRelationshipsPrices.ts';
import { SubscriptionRelationshipsPromotionalOffers } from '../models/SubscriptionRelationshipsPromotionalOffers.ts';
import { SubscriptionRelationshipsSubscriptionAvailability } from '../models/SubscriptionRelationshipsSubscriptionAvailability.ts';
import { SubscriptionRelationshipsSubscriptionLocalizations } from '../models/SubscriptionRelationshipsSubscriptionLocalizations.ts';
import { HttpFile } from '../http/http.ts';

export class SubscriptionRelationships {
    'subscriptionLocalizations'?: SubscriptionRelationshipsSubscriptionLocalizations;
    'appStoreReviewScreenshot'?: SubscriptionRelationshipsAppStoreReviewScreenshot;
    'group'?: SubscriptionGroupLocalizationRelationshipsSubscriptionGroup;
    'introductoryOffers'?: SubscriptionRelationshipsIntroductoryOffers;
    'promotionalOffers'?: SubscriptionRelationshipsPromotionalOffers;
    'offerCodes'?: SubscriptionRelationshipsOfferCodes;
    'prices'?: SubscriptionRelationshipsPrices;
    'promotedPurchase'?: InAppPurchaseV2RelationshipsPromotedPurchase;
    'subscriptionAvailability'?: SubscriptionRelationshipsSubscriptionAvailability;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "subscriptionLocalizations",
            "baseName": "subscriptionLocalizations",
            "type": "SubscriptionRelationshipsSubscriptionLocalizations",
            "format": ""
        },
        {
            "name": "appStoreReviewScreenshot",
            "baseName": "appStoreReviewScreenshot",
            "type": "SubscriptionRelationshipsAppStoreReviewScreenshot",
            "format": ""
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "SubscriptionGroupLocalizationRelationshipsSubscriptionGroup",
            "format": ""
        },
        {
            "name": "introductoryOffers",
            "baseName": "introductoryOffers",
            "type": "SubscriptionRelationshipsIntroductoryOffers",
            "format": ""
        },
        {
            "name": "promotionalOffers",
            "baseName": "promotionalOffers",
            "type": "SubscriptionRelationshipsPromotionalOffers",
            "format": ""
        },
        {
            "name": "offerCodes",
            "baseName": "offerCodes",
            "type": "SubscriptionRelationshipsOfferCodes",
            "format": ""
        },
        {
            "name": "prices",
            "baseName": "prices",
            "type": "SubscriptionRelationshipsPrices",
            "format": ""
        },
        {
            "name": "promotedPurchase",
            "baseName": "promotedPurchase",
            "type": "InAppPurchaseV2RelationshipsPromotedPurchase",
            "format": ""
        },
        {
            "name": "subscriptionAvailability",
            "baseName": "subscriptionAvailability",
            "type": "SubscriptionRelationshipsSubscriptionAvailability",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

