/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsSubscription } from '../models/SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsSubscription.ts';
import { SubscriptionIntroductoryOfferInlineCreateRelationshipsTerritory } from '../models/SubscriptionIntroductoryOfferInlineCreateRelationshipsTerritory.ts';
import { SubscriptionPriceCreateRequestDataRelationshipsSubscriptionPricePoint } from '../models/SubscriptionPriceCreateRequestDataRelationshipsSubscriptionPricePoint.ts';
import { HttpFile } from '../http/http.ts';

export class SubscriptionPriceCreateRequestDataRelationships {
    'subscription': SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsSubscription;
    'territory'?: SubscriptionIntroductoryOfferInlineCreateRelationshipsTerritory;
    'subscriptionPricePoint': SubscriptionPriceCreateRequestDataRelationshipsSubscriptionPricePoint;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsSubscription",
            "format": ""
        },
        {
            "name": "territory",
            "baseName": "territory",
            "type": "SubscriptionIntroductoryOfferInlineCreateRelationshipsTerritory",
            "format": ""
        },
        {
            "name": "subscriptionPricePoint",
            "baseName": "subscriptionPricePoint",
            "type": "SubscriptionPriceCreateRequestDataRelationshipsSubscriptionPricePoint",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionPriceCreateRequestDataRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

