/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubscriptionOfferCodePriceInlineCreateRelationships } from '../models/SubscriptionOfferCodePriceInlineCreateRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class SubscriptionOfferCodePriceInlineCreate {
    'type': SubscriptionOfferCodePriceInlineCreateTypeEnum;
    'id'?: string;
    'relationships'?: SubscriptionOfferCodePriceInlineCreateRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SubscriptionOfferCodePriceInlineCreateTypeEnum",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "SubscriptionOfferCodePriceInlineCreateRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionOfferCodePriceInlineCreate.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SubscriptionOfferCodePriceInlineCreateTypeEnum {
    SubscriptionOfferCodePrices = 'subscriptionOfferCodePrices'
}

