/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AppAvailabilityCreateRequestDataRelationshipsAvailableTerritories } from '../models/AppAvailabilityCreateRequestDataRelationshipsAvailableTerritories.ts';
import { SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsSubscription } from '../models/SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsSubscription.ts';
import { HttpFile } from '../http/http.ts';

export class SubscriptionAvailabilityCreateRequestDataRelationships {
    'subscription': SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsSubscription;
    'availableTerritories': AppAvailabilityCreateRequestDataRelationshipsAvailableTerritories;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "SubscriptionAppStoreReviewScreenshotCreateRequestDataRelationshipsSubscription",
            "format": ""
        },
        {
            "name": "availableTerritories",
            "baseName": "availableTerritories",
            "type": "AppAvailabilityCreateRequestDataRelationshipsAvailableTerritories",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionAvailabilityCreateRequestDataRelationships.attributeTypeMap;
    }

    public constructor() {
    }
}

