/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubscriptionGroupLocalizationCreateRequestDataAttributes } from '../models/SubscriptionGroupLocalizationCreateRequestDataAttributes.ts';
import { SubscriptionGroupLocalizationCreateRequestDataRelationships } from '../models/SubscriptionGroupLocalizationCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class SubscriptionGroupLocalizationCreateRequestData {
    'type': SubscriptionGroupLocalizationCreateRequestDataTypeEnum;
    'attributes': SubscriptionGroupLocalizationCreateRequestDataAttributes;
    'relationships': SubscriptionGroupLocalizationCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SubscriptionGroupLocalizationCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "SubscriptionGroupLocalizationCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "SubscriptionGroupLocalizationCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionGroupLocalizationCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SubscriptionGroupLocalizationCreateRequestDataTypeEnum {
    SubscriptionGroupLocalizations = 'subscriptionGroupLocalizations'
}

