/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DocumentLinks } from '../models/DocumentLinks.ts';
import { SubscriptionGroup } from '../models/SubscriptionGroup.ts';
import { SubscriptionGroupsResponseIncludedInner } from '../models/SubscriptionGroupsResponseIncludedInner.ts';
import { HttpFile } from '../http/http.ts';

export class SubscriptionGroupResponse {
    'data': SubscriptionGroup;
    'included'?: Array<SubscriptionGroupsResponseIncludedInner>;
    'links': DocumentLinks;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "data",
            "baseName": "data",
            "type": "SubscriptionGroup",
            "format": ""
        },
        {
            "name": "included",
            "baseName": "included",
            "type": "Array<SubscriptionGroupsResponseIncludedInner>",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "DocumentLinks",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionGroupResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

