/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SubscriptionOfferCodeCustomCodeCreateRequestDataAttributes } from '../models/SubscriptionOfferCodeCustomCodeCreateRequestDataAttributes.ts';
import { SubscriptionOfferCodeCustomCodeCreateRequestDataRelationships } from '../models/SubscriptionOfferCodeCustomCodeCreateRequestDataRelationships.ts';
import { HttpFile } from '../http/http.ts';

export class SubscriptionOfferCodeCustomCodeCreateRequestData {
    'type': SubscriptionOfferCodeCustomCodeCreateRequestDataTypeEnum;
    'attributes': SubscriptionOfferCodeCustomCodeCreateRequestDataAttributes;
    'relationships': SubscriptionOfferCodeCustomCodeCreateRequestDataRelationships;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "SubscriptionOfferCodeCustomCodeCreateRequestDataTypeEnum",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "SubscriptionOfferCodeCustomCodeCreateRequestDataAttributes",
            "format": ""
        },
        {
            "name": "relationships",
            "baseName": "relationships",
            "type": "SubscriptionOfferCodeCustomCodeCreateRequestDataRelationships",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionOfferCodeCustomCodeCreateRequestData.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SubscriptionOfferCodeCustomCodeCreateRequestDataTypeEnum {
    SubscriptionOfferCodeCustomCodes = 'subscriptionOfferCodeCustomCodes'
}

