/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpHeader } from '../models/HttpHeader.ts';
import { HttpFile } from '../http/http.ts';

export class UploadOperation {
    'method'?: string;
    'url'?: string;
    'length'?: number;
    'offset'?: number;
    'requestHeaders'?: Array<HttpHeader>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "method",
            "baseName": "method",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": ""
        },
        {
            "name": "length",
            "baseName": "length",
            "type": "number",
            "format": ""
        },
        {
            "name": "offset",
            "baseName": "offset",
            "type": "number",
            "format": ""
        },
        {
            "name": "requestHeaders",
            "baseName": "requestHeaders",
            "type": "Array<HttpHeader>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UploadOperation.attributeTypeMap;
    }

    public constructor() {
    }
}

