/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export enum UserRole {
    Admin = 'ADMIN',
    Finance = 'FINANCE',
    AccountHolder = 'ACCOUNT_HOLDER',
    Sales = 'SALES',
    Marketing = 'MARKETING',
    AppManager = 'APP_MANAGER',
    Developer = 'DEVELOPER',
    AccessToReports = 'ACCESS_TO_REPORTS',
    CustomerSupport = 'CUSTOMER_SUPPORT',
    ImageManager = 'IMAGE_MANAGER',
    CreateApps = 'CREATE_APPS',
    CloudManagedDeveloperId = 'CLOUD_MANAGED_DEVELOPER_ID',
    CloudManagedAppDistribution = 'CLOUD_MANAGED_APP_DISTRIBUTION',
    GenerateIndividualKeys = 'GENERATE_INDIVIDUAL_KEYS'
}
