/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricCategory } from '../models/MetricCategory.ts';
import { XcodeMetricsProductDataInnerMetricCategoriesInnerMetricsInner } from '../models/XcodeMetricsProductDataInnerMetricCategoriesInnerMetricsInner.ts';
import { HttpFile } from '../http/http.ts';

export class XcodeMetricsProductDataInnerMetricCategoriesInner {
    'identifier'?: MetricCategory;
    'metrics'?: Array<XcodeMetricsProductDataInnerMetricCategoriesInnerMetricsInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "identifier",
            "baseName": "identifier",
            "type": "MetricCategory",
            "format": ""
        },
        {
            "name": "metrics",
            "baseName": "metrics",
            "type": "Array<XcodeMetricsProductDataInnerMetricCategoriesInnerMetricsInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return XcodeMetricsProductDataInnerMetricCategoriesInner.attributeTypeMap;
    }

    public constructor() {
    }
}



