/**
 * App Store Connect API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 3.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { XcodeMetricsInsights } from '../models/XcodeMetricsInsights.ts';
import { XcodeMetricsProductDataInner } from '../models/XcodeMetricsProductDataInner.ts';
import { HttpFile } from '../http/http.ts';

export class XcodeMetrics {
    'version'?: string;
    'insights'?: XcodeMetricsInsights;
    'productData'?: Array<XcodeMetricsProductDataInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "insights",
            "baseName": "insights",
            "type": "XcodeMetricsInsights",
            "format": ""
        },
        {
            "name": "productData",
            "baseName": "productData",
            "type": "Array<XcodeMetricsProductDataInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return XcodeMetrics.attributeTypeMap;
    }

    public constructor() {
    }
}

