name: ci

on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno task lint

      - name: Run check
        run: deno task check

      - name: Run format
        run: deno task fmt:check
