name: ci

on:
  pull_request:
  merge_group:
  push:
    tags:
      - v*.*.*
      - dry-run-v*.*.*

permissions:
  contents: read

jobs:
  validation:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linter
        run: deno task lint

      - name: Run check
        run: deno task check

      - name: Run format
        run: deno task fmt:check

  publish:
    runs-on: ubuntu-latest

    needs: validation

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    permissions:
      contents: read
      id-token: write

    env:
      DRY_RUN: "false"

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Version check
        run: tools/check_version_tag.ts "${{ github.ref }}"

      - run: |
          echo "github.ref=${{ github.ref }}"
          if echo "${{ github.ref }}" | grep "dry-run"; then
            echo "Running dry-run"
            echo "DRY_RUN=true" >> $GITHUB_ENV
          else
            echo "Running publish"
            echo "DRY_RUN=false" >> $GITHUB_ENV
          fi

      - name: Run publish --dry-run
        if: ${{ env.DRY_RUN == 'true' }}
        run: deno publish --dry-run

      - name: Run publish
        if: ${{ env.DRY_RUN == 'false' }}
        run: deno publish
